export const dynamicData = [
  {
    id: 2,
    target: "Sample Target 1 1",
    sub_target: "Sample Sub Target 1 1",
    incorporation_city: "Sample City 1 1",
    sector_classification: "Sample Classification 1 1",
  },
  {
    id: 4,
    target: "Sample Target 2 2",
    sub_target: "Sample Sub Target 2 2",
    incorporation_city: "Sample City 2 2",
    sector_classification: "Sample Classification 2 2",
  },
  {
    id: 6,
    target: "Sample Target 3 3",
    sub_target: "Sample Sub Target 3 3",
    incorporation_city: "Sample City 3 3",
    sector_classification: "Sample Classification 3 3",
  },
  {
    id: 5,
    target: "Sample Target 1 4",
    sub_target: "Sample Sub Target 1 4",
    incorporation_city: "Sample City 1 4",
    sector_classification: "Sample Classification 1 4",
  },
  {
    id: 7,
    target: "Sample Target 2 5",
    sub_target: "Sample Sub Target 2 5",
    incorporation_city: "Sample City 2 5",
    sector_classification: "Sample Classification 2 5",
  },
  {
    id: 9,
    target: "Sample Target 3 6",
    sub_target: "Sample Sub Target 3 6",
    incorporation_city: "Sample City 3 6",
    sector_classification: "Sample Classification 3 6",
  },
  {
    id: 8,
    target: "Sample Target 1 7",
    sub_target: "Sample Sub Target 1 7",
    incorporation_city: "Sample City 1 7",
    sector_classification: "Sample Classification 1 7",
  },
  {
    id: 10,
    target: "Sample Target 2 8",
    sub_target: "Sample Sub Target 2 8",
    incorporation_city: "Sample City 2 8",
    sector_classification: "Sample Classification 2 8",
  },
  {
    id: 12,
    target: "Sample Target 3 9",
    sub_target: "Sample Sub Target 3 9",
    incorporation_city: "Sample City 3 9",
    sector_classification: "Sample Classification 3 9",
  },
  {
    id: 11,
    target: "Sample Target 1 10",
    sub_target: "Sample Sub Target 1 10",
    incorporation_city: "Sample City 1 10",
    sector_classification: "Sample Classification 1 10",
  },
  {
    id: 13,
    target: "Sample Target 2 11",
    sub_target: "Sample Sub Target 2 11",
    incorporation_city: "Sample City 2 11",
    sector_classification: "Sample Classification 2 11",
  },
  {
    id: 15,
    target: "Sample Target 3 12",
    sub_target: "Sample Sub Target 3 12",
    incorporation_city: "Sample City 3 12",
    sector_classification: "Sample Classification 3 12",
  },
  {
    id: 14,
    target: "Sample Target 1 13",
    sub_target: "Sample Sub Target 1 13",
    incorporation_city: "Sample City 1 13",
    sector_classification: "Sample Classification 1 13",
  },
  {
    id: 16,
    target: "Sample Target 2 14",
    sub_target: "Sample Sub Target 2 14",
    incorporation_city: "Sample City 2 14",
    sector_classification: "Sample Classification 2 14",
  },
  {
    id: 18,
    target: "Sample Target 3 15",
    sub_target: "Sample Sub Target 3 15",
    incorporation_city: "Sample City 3 15",
    sector_classification: "Sample Classification 3 15",
  },
  {
    id: 17,
    target: "Sample Target 1 16",
    sub_target: "Sample Sub Target 1 16",
    incorporation_city: "Sample City 1 16",
    sector_classification: "Sample Classification 1 16",
  },
  {
    id: 19,
    target: "Sample Target 2 17",
    sub_target: "Sample Sub Target 2 17",
    incorporation_city: "Sample City 2 17",
    sector_classification: "Sample Classification 2 17",
  },
  {
    id: 21,
    target: "Sample Target 3 18",
    sub_target: "Sample Sub Target 3 18",
    incorporation_city: "Sample City 3 18",
    sector_classification: "Sample Classification 3 18",
  },
  {
    id: 20,
    target: "Sample Target 1 19",
    sub_target: "Sample Sub Target 1 19",
    incorporation_city: "Sample City 1 19",
    sector_classification: "Sample Classification 1 19",
  },
  {
    id: 22,
    target: "Sample Target 2 20",
    sub_target: "Sample Sub Target 2 20",
    incorporation_city: "Sample City 2 20",
    sector_classification: "Sample Classification 2 20",
  },
  {
    id: 24,
    target: "Sample Target 3 21",
    sub_target: "Sample Sub Target 3 21",
    incorporation_city: "Sample City 3 21",
    sector_classification: "Sample Classification 3 21",
  },
  {
    id: 23,
    target: "Sample Target 1 22",
    sub_target: "Sample Sub Target 1 22",
    incorporation_city: "Sample City 1 22",
    sector_classification: "Sample Classification 1 22",
  },
  {
    id: 25,
    target: "Sample Target 2 23",
    sub_target: "Sample Sub Target 2 23",
    incorporation_city: "Sample City 2 23",
    sector_classification: "Sample Classification 2 23",
  },
  {
    id: 27,
    target: "Sample Target 3 24",
    sub_target: "Sample Sub Target 3 24",
    incorporation_city: "Sample City 3 24",
    sector_classification: "Sample Classification 3 24",
  },
  {
    id: 26,
    target: "Sample Target 1 25",
    sub_target: "Sample Sub Target 1 25",
    incorporation_city: "Sample City 1 25",
    sector_classification: "Sample Classification 1 25",
  },
  {
    id: 28,
    target: "Sample Target 2 26",
    sub_target: "Sample Sub Target 2 26",
    incorporation_city: "Sample City 2 26",
    sector_classification: "Sample Classification 2 26",
  },
  {
    id: 30,
    target: "Sample Target 3 27",
    sub_target: "Sample Sub Target 3 27",
    incorporation_city: "Sample City 3 27",
    sector_classification: "Sample Classification 3 27",
  },
  {
    id: 29,
    target: "Sample Target 1 28",
    sub_target: "Sample Sub Target 1 28",
    incorporation_city: "Sample City 1 28",
    sector_classification: "Sample Classification 1 28",
  },
  {
    id: 31,
    target: "Sample Target 2 29",
    sub_target: "Sample Sub Target 2 29",
    incorporation_city: "Sample City 2 29",
    sector_classification: "Sample Classification 2 29",
  },
  {
    id: 33,
    target: "Sample Target 3 30",
    sub_target: "Sample Sub Target 3 30",
    incorporation_city: "Sample City 3 30",
    sector_classification: "Sample Classification 3 30",
  },
  {
    id: 32,
    target: "Sample Target 1 31",
    sub_target: "Sample Sub Target 1 31",
    incorporation_city: "Sample City 1 31",
    sector_classification: "Sample Classification 1 31",
  },
  {
    id: 34,
    target: "Sample Target 2 32",
    sub_target: "Sample Sub Target 2 32",
    incorporation_city: "Sample City 2 32",
    sector_classification: "Sample Classification 2 32",
  },
  {
    id: 36,
    target: "Sample Target 3 33",
    sub_target: "Sample Sub Target 3 33",
    incorporation_city: "Sample City 3 33",
    sector_classification: "Sample Classification 3 33",
  },
  {
    id: 35,
    target: "Sample Target 1 34",
    sub_target: "Sample Sub Target 1 34",
    incorporation_city: "Sample City 1 34",
    sector_classification: "Sample Classification 1 34",
  },
  {
    id: 37,
    target: "Sample Target 2 35",
    sub_target: "Sample Sub Target 2 35",
    incorporation_city: "Sample City 2 35",
    sector_classification: "Sample Classification 2 35",
  },
  {
    id: 39,
    target: "Sample Target 3 36",
    sub_target: "Sample Sub Target 3 36",
    incorporation_city: "Sample City 3 36",
    sector_classification: "Sample Classification 3 36",
  },
  {
    id: 38,
    target: "Sample Target 1 37",
    sub_target: "Sample Sub Target 1 37",
    incorporation_city: "Sample City 1 37",
    sector_classification: "Sample Classification 1 37",
  },
  {
    id: 40,
    target: "Sample Target 2 38",
    sub_target: "Sample Sub Target 2 38",
    incorporation_city: "Sample City 2 38",
    sector_classification: "Sample Classification 2 38",
  },
];
